//
Mandatory:

1. Use try and catch block to satisfy exceptional handling techniques.
2. Inside catch method use the following class in the argument

catch(ArithmeticException e)

3. Print the ArithmeticException object "e" using

System.out.println(e) and it will return the output as follows "java.lang.ArithmeticException: / by zero"
Logic Test Case 1

Input (stdin)
78

12

Expected Output

6
Logic Test Case 2

Input (stdin)
56

0

Expected Output

java.lang.ArithmeticException: / by zero
Mandatory Test Cases

Test Case 1
catch(ArithmeticException e)
Test Case 2
System.out.println(e);
//



import java.util.*;
public class TestClass {
	 public static void main(String[] args) { 
       Scanner in=new Scanner(System.in);
       try
       { 
         int a,b;
         a=in.nextInt();
         b=in.nextInt();
         int c=a/b;
         System.out.println(c);
       } 
       catch(ArithmeticException e) 
       { 
         System.out.println(e);
       }
		
	}
}
